name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.FINUT_SSH_KEY }}
          host: ${{ secrets.FINUT_EC2_HOST }}
          username: ${{ secrets.FINUT_EC2_USER }} 
          script: |
            cd app
            ./deploy.sh
